-- 1. Create Sales Header Table (if not exists)
CREATE TABLE IF NOT EXISTS public.pharmacy_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    customer_phone TEXT,
    patient_id TEXT, 
    doctor_name TEXT,
    payment_mode TEXT DEFAULT 'Cash',
    paid_amount_cash NUMERIC DEFAULT 0,
    paid_amount_online NUMERIC DEFAULT 0,
    subtotal NUMERIC NOT NULL DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    curr_total NUMERIC NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'completed',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create Sales Items Table (if not exists)
CREATE TABLE IF NOT EXISTS public.pharmacy_sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.pharmacy_sales(id) ON DELETE CASCADE,
    inventory_id BIGINT, 
    medicine_id BIGINT,
    batch_number TEXT,
    expiry_date DATE,
    quantity NUMERIC NOT NULL, 
    quantity_mode TEXT DEFAULT 'Pack', 
    pack_size_quantity INTEGER DEFAULT 1, 
    total_units_sold INTEGER DEFAULT 0, 
    unit_price NUMERIC NOT NULL,
    total_price NUMERIC NOT NULL,
    discount_amount NUMERIC DEFAULT 0, -- Store item level discount
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Add discount_amount column if missing (Migration Step)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'pharmacy_sale_items'
        AND column_name = 'discount_amount'
    ) THEN
        ALTER TABLE public.pharmacy_sale_items ADD COLUMN discount_amount NUMERIC DEFAULT 0;
    END IF;
END $$;

-- 4. Create Index (Wait for column addition first)
CREATE INDEX IF NOT EXISTS idx_pharmacy_sales_patient ON public.pharmacy_sales(patient_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_sales_date ON public.pharmacy_sales(created_at);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON public.pharmacy_sale_items(sale_id);

-- 5. Update the RPC Function
CREATE OR REPLACE FUNCTION save_sales_entry(
    p_customer_name text,
    p_customer_phone text,
    p_patient_id text,
    p_doctor_name text,
    p_payment_mode text,
    p_paid_cash numeric,
    p_paid_online numeric,
    p_subtotal numeric,
    p_discount_amount numeric,
    p_final_total numeric,
    p_items jsonb,
    p_notes text DEFAULT ''
)
RETURNS json
LANGUAGE plpgsql
AS $$
DECLARE
    v_sale_id bigint;
    v_item jsonb;
    v_current_stock_units integer;
    v_new_stock_units integer;
BEGIN
    -- Insert Sales Header
    INSERT INTO pharmacy_sales (
        customer_name, customer_phone, patient_id, doctor_name,
        payment_mode, paid_amount_cash, paid_amount_online,
        subtotal, discount_amount, curr_total, notes, status, created_at
    ) VALUES (
        p_customer_name, p_customer_phone, p_patient_id, p_doctor_name,
        p_payment_mode, p_paid_cash, p_paid_online,
        p_subtotal, p_discount_amount, p_final_total, p_notes, 'completed', now()
    ) RETURNING id INTO v_sale_id;

    -- Process Items
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        -- Check Stock
        SELECT remaining_units INTO v_current_stock_units
        FROM pharmacy_batch_stock
        WHERE medicine_id = (v_item->>'medicine_id')::bigint 
          AND batch_number = (v_item->>'batch_number');

        IF v_current_stock_units IS NULL THEN
            RAISE EXCEPTION 'Batch % not found for Medicine ID %', (v_item->>'batch_number'), (v_item->>'medicine_id');
        END IF;

        IF v_current_stock_units < (v_item->>'total_units_sold')::integer THEN
             RAISE EXCEPTION 'Insufficient stock for Batch %. Available: %', (v_item->>'batch_number'), v_current_stock_units;
        END IF;

        -- Deduct Stock
        v_new_stock_units := v_current_stock_units - (v_item->>'total_units_sold')::integer;

        UPDATE pharmacy_batch_stock
        SET remaining_units = v_new_stock_units,
            quantity = FLOOR(v_new_stock_units / GREATEST(pack_size_quantity, 1))
        WHERE medicine_id = (v_item->>'medicine_id')::bigint 
          AND batch_number = (v_item->>'batch_number');

        -- Insert Item
        INSERT INTO pharmacy_sale_items (
            sale_id, medicine_id, quantity, unit_price, total_price,
            batch_number, expiry_date, pack_size_quantity, quantity_mode, total_units_sold, discount_amount
        ) VALUES (
            v_sale_id,
            (v_item->>'medicine_id')::bigint,
            (v_item->>'quantity')::numeric,
            (v_item->>'unit_price')::numeric,
            (v_item->>'total_price')::numeric,
            (v_item->>'batch_number'),
            (v_item->>'expiry_date')::date,
            (v_item->>'pack_size_quantity')::integer,
            (v_item->>'quantity_mode'),
            (v_item->>'total_units_sold')::integer,
            COALESCE((v_item->>'discount_amount')::numeric, 0)
        );
    END LOOP;

    RETURN json_build_object('sale_id', v_sale_id, 'status', 'success');
END;
$$;

-- 6. Reload Schema
NOTIFY pgrst, 'reload schema';
