-- Inserting Services for X-RAY, PROCEDURES, DOPPLER, SONOGRAPHY

INSERT INTO zblood_test (test_name, price, type, estimated_time_mm, outsource, parameter, sub_heading) VALUES
-- X-RAY OR DIGITAL
('CHEST PA /AP/LAT/OBL', 250, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('ABDOMEN SUPINE/ERECT', 250, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('ABDOMEN ERECT', 250, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('KUB', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('LUMBER SACRAL SPINEAP/LAT', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('CERVICAL SPINE AP/LAT', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('DORSAL SPINE AP/LAT', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('SKULL AP/LAT', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('PNS(W & C)', 500, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('SHOULDER AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('CLAVICLE', 250, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('WRIST AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('NASOPHARYNX / ADENOID', 250, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('KNEE JOINT AP/ LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('ANKLE JOINT AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('FOOT AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('ELBOW AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('FOREAR AP/LAT', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),
('MASTOID', 350, 'xray_standard', '0', false, '[]'::jsonb, '[]'::jsonb),

-- X-RAY PROCEDURE
('BARIUM SWALLOW', 1200, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('BARIUM MEAL STOM/DUO', 1500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('BARIUM IC JTN /APPENDIX', 1800, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('IVP', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('SINOGRAM', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('HSG', 3000, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('SIALOGRAM', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('BARIUM ENEMA', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('URETHROGRAM', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('FISTULOGRAM', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('RGU', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),
('MCU', 3500, 'xray_procedure', '0', false, '[]'::jsonb, '[]'::jsonb),

-- COLOR DOPPLER
('UPPER LIMBS(A/V)', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('LOWER LIMBS', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('OBSTERIC DOPPLER', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('CAROTID DOPPLER', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('DOPPLER for AV fistula', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('PORTAL VENOUS DOPPLER', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('RENAL DOPPLER', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('SCROTAL DOPPLER', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('2 D ECHO', 2000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('E.C.G', 350, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('NST', 500, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('TOTAL BODY PROF (MINI)', 3000, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('TOTAL BODY PROF (REGULAR) X-RAY &USG', 4500, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),
('TOTAL BODY PROF(MAXI)(MINI + REGULAR+OTHER TEST)', 8500, 'color_doppler', '0', false, '[]'::jsonb, '[]'::jsonb),

-- MISC PROFILES / BLOOD TESTS
('COAGULATION PROFILE', 3000, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),
('PCOS PROFILE', 3000, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),
('ARTHRITIS PROFILE', 3000, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),
('TROP T/I', 1200, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),
('CARDIOLIPIN PROFILE', 3450, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),
('ENTAMEABA IGG', 1500, 'blood_test', '0', false, '[]'::jsonb, '[]'::jsonb),

-- SONOGRAPHY
('FULL ABDOMEN', 1200, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('UPPER ABDOME', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('URINARY SYSTEM KUB', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('FOLLICULAR STUDY', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('PELVIS', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('PELVIS WITH TRANVAGINAL', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('FULL ABDOMEN WITH OBST', 1800, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('OBSTERIC SCAN', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('TWINS OBST', 1800, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('NT SCAN(EARLY ANOMALY)', 1500, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('TWINS ANOMALY', 4000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('TWINS COLOR DOPPLER', 4000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('ANOMALY SCAN', 2000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('FULL ABDO WITH ANOMALY SCAN', 3200, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('ANOMALY SCAN WITH 3D', 4000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('ANOMALY SCAN WITH 4 D', 4000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('BIOPHYSISAL SCORE', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('ELASTROGRAPHY', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('NECK', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('THYROID', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('SCROTUM', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('SINGLE BREAST(MOMOGRAPHY)', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('BOTH BREAST(MOMOGRAPHY)', 2000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('CHEST USG', 1000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb),
('4D ULTRASONOGRAPHY', 4000, 'sonography', '0', false, '[]'::jsonb, '[]'::jsonb);
