-- 1. Create the Advanced Associations Table
-- This table stores a highly granular mapping of clinical data points.
-- We now include 'context' field to store JSON data like age_group, gender, severity, etc.

DROP TABLE IF EXISTS opd_ai_associations;

CREATE TABLE IF NOT EXISTS opd_ai_associations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Source (The Input)
    source_type TEXT NOT NULL, -- 'symptom', 'diagnosis', 'age_group', 'gender'
    source_value TEXT NOT NULL,
    source_meta JSONB, -- Stores severity, duration, etc. e.g. { "severity": "High", "duration": "short" }
    
    -- Target (The Output)
    target_type TEXT NOT NULL, -- 'diagnosis', 'medicine', 'investigation', 'instruction', 'procedure'
    target_value TEXT NOT NULL,
    
    weight INTEGER DEFAULT 1,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    
    -- Composite unique constraint to prevent duplicates
    -- We include a hash of source_meta for uniqueness if meta matters for distinct rows, 
    -- OR we keep it simpler and just aggregate by main types. 
    -- For high accuracy, we should probably stick to main pairings but boost weights based on matching meta.
    -- To keep it performant and manageable:
    UNIQUE(source_type, source_value, target_type, target_value)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_ai_source_v2 ON opd_ai_associations(source_type, source_value);
CREATE INDEX IF NOT EXISTS idx_ai_target_v2 ON opd_ai_associations(target_type, target_value);


-- 2. Advanced Learning Function
-- This function digests the entire prescription including Age, Gender, Severity, etc.

CREATE OR REPLACE FUNCTION learn_from_prescription_v2(
    p_age_group TEXT, -- 'child', 'adult', 'senior'
    p_gender TEXT,    -- 'male', 'female'
    
    p_symptoms JSONB[], -- Array of objects: { name, severity, duration }
    p_diagnoses JSONB[], -- Array of objects: { name, status }
    
    p_medicines TEXT[], 
    p_investigations TEXT[],
    p_instructions TEXT[],
    p_procedures TEXT[]
)
RETURNS VOID AS $$
DECLARE
    s JSONB;
    d JSONB;
    m TEXT;
    inv TEXT;
    inst TEXT;
    proc TEXT;
    
    s_name TEXT;
    d_name TEXT;
BEGIN
    -- A. Contextual Learning (Demographics -> All Outputs)
    -- Link Age/Gender to Diagnoses (e.g. Chicken Pox more common in kids)
    -- Start with simple meta for demographics (optional, or just null)
    FOREACH d IN ARRAY p_diagnoses LOOP
        d_name := d->>'name';
        
        -- Age -> Diagnosis
        INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
        VALUES ('age_group', p_age_group, null, 'diagnosis', d_name, 1)
        ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;

        -- Gender -> Diagnosis
        INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
        VALUES ('gender', p_gender, null, 'diagnosis', d_name, 1)
        ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
    END LOOP;

    -- B. Symptom Deep Learning (Symptom + Severity -> Diagnosis/Medicine)
    FOREACH s IN ARRAY p_symptoms LOOP
        s_name := s->>'name';
        
        -- 1. Symptom -> Diagnosis
        FOREACH d IN ARRAY p_diagnoses LOOP
            d_name := d->>'name';
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('symptom', s_name, s, 'diagnosis', d_name, 1) -- 's' is the full JSON Object {name, severity, duration}
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;

        -- 2. Symptom -> Medicine
        FOREACH m IN ARRAY p_medicines LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('symptom', s_name, s, 'medicine', m, 1)
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;
        
        -- 3. Symptom -> Investigation/Instruction
        FOREACH inv IN ARRAY p_investigations LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('symptom', s_name, s, 'investigation', inv, 1)
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;
    END LOOP;

    -- C. Diagnosis Driven Learning (Diagnosis -> Treatment Plan)
    FOREACH d IN ARRAY p_diagnoses LOOP
        d_name := d->>'name';

        -- Diagnosis -> Medicine
        FOREACH m IN ARRAY p_medicines LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('diagnosis', d_name, d, 'medicine', m, 1) -- 'd' is the full JSON Object {name, status}
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;

        -- Diagnosis -> Investigation
        FOREACH inv IN ARRAY p_investigations LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('diagnosis', d_name, d, 'investigation', inv, 1)
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;

        -- Diagnosis -> Instruction
        FOREACH inst IN ARRAY p_instructions LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('diagnosis', d_name, d, 'instruction', inst, 1)
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;
        
        -- Diagnosis -> Procedure
        FOREACH proc IN ARRAY p_procedures LOOP
            INSERT INTO opd_ai_associations (source_type, source_value, source_meta, target_type, target_value, weight)
            VALUES ('diagnosis', d_name, d, 'procedure', proc, 1)
            ON CONFLICT (source_type, source_value, target_type, target_value) DO UPDATE SET weight = opd_ai_associations.weight + 1;
        END LOOP;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
