-- 1. Create the Associations Table
-- This table stores the strength of relationships between items.
-- Example: ('symptom', 'Fever', 'diagnosis', 'Viral Fever', 5) means they appeared together 5 times.

CREATE TABLE IF NOT EXISTS opd_ai_associations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL, -- 'symptom' or 'diagnosis'
    source_value TEXT NOT NULL,
    target_type TEXT NOT NULL, -- 'diagnosis' or 'medicine'
    target_value TEXT NOT NULL,
    weight INTEGER DEFAULT 1,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure unique pairs so we can increment safely
    UNIQUE(source_type, source_value, target_type, target_value)
);

-- Index for fast lookups during prediction
CREATE INDEX IF NOT EXISTS idx_ai_source ON opd_ai_associations(source_type, source_value);

-- 2. Create the Learning Function (RPC)
-- This function takes the final prescription data and updates all relevant counters in one go.

CREATE OR REPLACE FUNCTION learn_from_prescription(
    p_symptoms TEXT[],
    p_diagnoses TEXT[],
    p_medicines TEXT[]
)
RETURNS VOID AS $$
DECLARE
    s TEXT;
    d TEXT;
    m TEXT;
BEGIN
    -- A. Link Symptoms -> Diagnoses
    IF array_length(p_symptoms, 1) > 0 AND array_length(p_diagnoses, 1) > 0 THEN
        FOREACH s IN ARRAY p_symptoms LOOP
            FOREACH d IN ARRAY p_diagnoses LOOP
                INSERT INTO opd_ai_associations (source_type, source_value, target_type, target_value, weight)
                VALUES ('symptom', s, 'diagnosis', d, 1)
                ON CONFLICT (source_type, source_value, target_type, target_value)
                DO UPDATE SET weight = opd_ai_associations.weight + 1, last_updated = NOW();
            END LOOP;
        END LOOP;
    END IF;

    -- B. Link Symptoms -> Medicines (Direct Symptom Treatment)
    IF array_length(p_symptoms, 1) > 0 AND array_length(p_medicines, 1) > 0 THEN
        FOREACH s IN ARRAY p_symptoms LOOP
            FOREACH m IN ARRAY p_medicines LOOP
                INSERT INTO opd_ai_associations (source_type, source_value, target_type, target_value, weight)
                VALUES ('symptom', s, 'medicine', m, 1)
                ON CONFLICT (source_type, source_value, target_type, target_value)
                DO UPDATE SET weight = opd_ai_associations.weight + 1, last_updated = NOW();
            END LOOP;
        END LOOP;
    END IF;

    -- C. Link Diagnoses -> Medicines (Standard Treatment Protocols)
    IF array_length(p_diagnoses, 1) > 0 AND array_length(p_medicines, 1) > 0 THEN
        FOREACH d IN ARRAY p_diagnoses LOOP
            FOREACH m IN ARRAY p_medicines LOOP
                INSERT INTO opd_ai_associations (source_type, source_value, target_type, target_value, weight)
                VALUES ('diagnosis', d, 'medicine', m, 1)
                ON CONFLICT (source_type, source_value, target_type, target_value)
                DO UPDATE SET weight = opd_ai_associations.weight + 1, last_updated = NOW();
            END LOOP;
        END LOOP;
    END IF;
END;
$$ LANGUAGE plpgsql;
